# Numpy

NumPy is a powerful Python library used for numerical computing, providing support for large, multi-dimensional arrays and high-performance mathematical operations.

In [2]:
import numpy as np

array = np.array([1, 2, 3])
print(array)
print(type(array))


[1 2 3]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

array = np.array([[1, 2, 3],[4,5,6]])
print(array)
print("array shape [rows, columns] : ",array.shape)

[[1 2 3]
 [4 5 6]]
array shape [rows, columns] :  (2, 3)


In [ ]:
import numpy as np

# Create a 3x4 array filled with zeros
array_1 = np.zeros((3, 4), dtype=int)
print("Array of zeros (3x4):")
print(array_1)
print()

# Create a 3x4 array filled with ones
array_2 = np.ones((3, 4), dtype=int)
print("Array of ones (3x4):")
print(array_2)
print()

# Create a 3x4 array filled with the number 5
array_3 = np.full((3, 4), 5, dtype=int)
print("Array filled with 5s (3x4):")
print(array_3)
print()





Array of zeros (3x4):
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Array of ones (3x4):
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Array filled with 5s (3x4):
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

Array with random floats (3x4):
[[0.9704488  0.96974433 0.90116318 0.98094648]
 [0.72156216 0.35456447 0.61304306 0.78150714]
 [0.11065941 0.2564855  0.71234378 0.11654124]]
0.9704487976484134


In [ ]:
import numpy as np

# Create a 3x4 array with random float numbers between 0 and 1
array_4 = np.random.random((3, 4))
print("Array with random floats (3x4):")
print(array_4)
print()

# Access and print the element at row 0, column 0
print("Element at index [0][0]:")
print(array_4[0, 0])
print()

# Boolean mask: check which elements are greater than 0.2
print("Boolean mask (array_4 > 0.2):")
print(array_4 > 0.2)
print()

# Print only the elements greater than 0.2
print("Elements in array_4 greater than 0.2:")
print(array_4[array_4 > 0.2])
print()

# Sum of all elements in the array
print("Sum of all elements in array_4:")
print(np.sum(array_4))
print()

# Rounded version of the array (each element rounded to nearest integer: 0 or 1)
print("Rounded array_4 (values rounded to nearest whole number):")
print(np.round(array_4))


Array with random floats (3x4):
[[0.70475196 0.4130349  0.21287807 0.72529744]
 [0.92895143 0.01907522 0.85665854 0.51678634]
 [0.7231543  0.85042132 0.3881637  0.69150075]]

Element at index [0][0]:
0.7047519637666565

Boolean mask (array_4 > 0.2):
[[ True  True  True  True]
 [ True False  True  True]
 [ True  True  True  True]]

Elements in array_4 greater than 0.2:
[0.70475196 0.4130349  0.21287807 0.72529744 0.92895143 0.85665854
 0.51678634 0.7231543  0.85042132 0.3881637  0.69150075]

Sum of all elements in array_4:
7.030673978787138

Rounded array_4 (values rounded to nearest whole number):
[[1. 0. 0. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]]


In [18]:
import numpy as np

first = np.array([[1, 2, 3], [4, 5, 6]])
print(first + 2)

[[3 4 5]
 [6 7 8]]


In [20]:
import numpy as np

# Using NumPy array to convert dimensions from inches to centimeters
dimensions_inch_1 = np.array([1, 2, 3])
dimensions_cm_1 = dimensions_inch_1 * 2.54
print(dimensions_cm_1)

# Using a regular Python list and list comprehension to do the same conversion
dimensions_inch_2 = [1, 2, 3]
dimensions_cm_2 = [x * 2.54 for x in dimensions_inch_2]
print(dimensions_cm_2)

[2.54 5.08 7.62]
[2.54, 5.08, 7.62]
